# -*- coding: utf-8 -*-
# Benchmark using Refactored Trainer Classes directly with PEFT support
# Includes detailed Time Profiling (Perturb/Forward/Update) and Memory Statistics

import os
import sys

current_dir = os.path.dirname(os.path.abspath(__file__))
parent_dir = os.path.dirname(current_dir)
sys.path.append(parent_dir)

import torch
import time
import numpy as np
import types
from fire import Fire
from transformers import AutoModelForCausalLM, AutoConfig, AutoTokenizer
from torch.utils.data import Dataset
from peft import get_peft_model, LoraConfig, TaskType

# Import modules from the refactored code (ZO_all_code)
from arguments import LMZOTrainingArguments
from zo_core.trainer import get_trainer_class

# =============================================================================
# 1. Profiled Step Functions
# =============================================================================

def profiled_mezo_step(self, model, inputs, num_items_in_batch=None):
    """
    MeZO training step with detailed timing profiling.
    Replaces trainer.training_step
    """
    stats = {"perturb": 0.0, "forward": 0.0, "update": 0.0}
    
    # 1. Sample Seed
    self.zo_random_seed = np.random.randint(1000000000)
    
    # === Perturb (+) ===
    torch.cuda.synchronize()
    t0 = time.perf_counter()
    self._perturb_mezo(scaling_factor=1)
    torch.cuda.synchronize()
    stats["perturb"] += time.perf_counter() - t0
    
    # === Forward (+) ===
    torch.cuda.synchronize()
    t0 = time.perf_counter()
    loss1 = self.zo_forward(model, inputs)
    torch.cuda.synchronize()
    stats["forward"] += time.perf_counter() - t0
    
    # === Perturb (-) ===
    # From +1 to -1 requires -2 step
    torch.cuda.synchronize()
    t0 = time.perf_counter()
    self._perturb_mezo(scaling_factor=-2)
    torch.cuda.synchronize()
    stats["perturb"] += time.perf_counter() - t0
    
    # === Forward (-) ===
    torch.cuda.synchronize()
    t0 = time.perf_counter()
    loss2 = self.zo_forward(model, inputs)
    torch.cuda.synchronize()
    stats["forward"] += time.perf_counter() - t0
    
    # Calculate Projected Gradient Estimate
    self.projected_grad = (loss1 - loss2) / (2 * self.args.zo_eps)
    
    # === Restore Parameters ===
    # From -1 back to 0 requires +1
    torch.cuda.synchronize()
    t0 = time.perf_counter()
    self._perturb_mezo(scaling_factor=1)
    torch.cuda.synchronize()
    stats["perturb"] += time.perf_counter() - t0
    
    # === Update Parameters ===
    torch.cuda.synchronize()
    t0 = time.perf_counter()
    self._update_mezo()
    torch.cuda.synchronize()
    stats["update"] += time.perf_counter() - t0
    
    # Save stats of this step to the trainer instance for external access
    self._last_step_stats = stats
    return loss1

def profiled_dizo_step(self, model, inputs, num_items_in_batch=None):
    """
    DiZO detailed time profiling.
    Uses MeZO step for the base update, then adds DiZO projection overhead.
    """
    # 1. Run Standard MeZO Step (updates model parameters)
    # This handles the basic Perturb/Forward/Update stats
    loss = profiled_mezo_step(self, model, inputs, num_items_in_batch)
    
    # Retrieve stats generated by the MeZO step
    stats = self._last_step_stats
    
    # 2. Periodic DiZO Projection
    # Logic matches DiZOTrainer.training_step
    if self.state.global_step > 0 and self.state.global_step % self.dizo_interval == 0:
        torch.cuda.synchronize()
        t0 = time.perf_counter()
        
        # We categorize the entire projection loop as "Update" overhead
        # since it's a constraint enforcement rather than gradient estimation.
        self.dizo_step(model, inputs)
        
        torch.cuda.synchronize()
        stats["update"] += time.perf_counter() - t0
        
        # Update the stats attached to the trainer
        self._last_step_stats = stats

    return loss
# =============================================================================
# Additional Profiled Step Functions for UnifiedZO Methods
# =============================================================================

def profiled_lozo_step(self, model, inputs, num_items_in_batch=None):
    """LoZO (Low-Rank ZO) detailed time profiling"""
    stats = {"perturb": 0.0, "forward": 0.0, "update": 0.0}
    
    # LoZO V Matrix Update (Per Interval) - Counted as Update overhead
    torch.cuda.synchronize()
    t0 = time.perf_counter()
    if self.state.global_step % self.args.lozo_step_interval == 0:
        self._update_lozo_v()
    torch.cuda.synchronize()
    stats["update"] += time.perf_counter() - t0

    self.zo_random_seed = np.random.randint(1000000000)
    
    # === Perturb (+) ===
    torch.cuda.synchronize()
    t0 = time.perf_counter()
    self._perturb_lozo(scaling_factor=1)
    torch.cuda.synchronize()
    stats["perturb"] += time.perf_counter() - t0
    
    # === Forward (+) ===
    torch.cuda.synchronize()
    t0 = time.perf_counter()
    loss1 = self.zo_forward(model, inputs)
    torch.cuda.synchronize()
    stats["forward"] += time.perf_counter() - t0
    
    # === Perturb (-) ===
    torch.cuda.synchronize()
    t0 = time.perf_counter()
    self._perturb_lozo(scaling_factor=-2) # +1 -> -1
    torch.cuda.synchronize()
    stats["perturb"] += time.perf_counter() - t0
    
    # === Forward (-) ===
    torch.cuda.synchronize()
    t0 = time.perf_counter()
    loss2 = self.zo_forward(model, inputs)
    torch.cuda.synchronize()
    stats["forward"] += time.perf_counter() - t0
    
    # Gradient Estimate Calculation
    self.projected_grad = ((loss1 - loss2) / (2 * self.args.zo_eps)).item()
    
    # === Restore (+) ===
    torch.cuda.synchronize()
    t0 = time.perf_counter()
    self._perturb_lozo(scaling_factor=1) # -1 -> 0
    torch.cuda.synchronize()
    stats["perturb"] += time.perf_counter() - t0
    
    # === Update ===
    torch.cuda.synchronize()
    t0 = time.perf_counter()
    self._update_lozo()
    torch.cuda.synchronize()
    stats["update"] += time.perf_counter() - t0
    
    self._last_step_stats = stats
    return loss1

def profiled_zo_adamu_step(self, model, inputs, num_items_in_batch=None):
    """ZO-AdaMU detailed time profiling"""
    stats = {"perturb": 0.0, "forward": 0.0, "update": 0.0}
    
    self.zo_random_seed = np.random.randint(1000000000)
    
    # === Perturb (+) ===
    torch.cuda.synchronize()
    t0 = time.perf_counter()
    self._perturb_parameters(scaling_factor=1)
    torch.cuda.synchronize()
    stats["perturb"] += time.perf_counter() - t0
    
    # === Forward (+) ===
    torch.cuda.synchronize()
    t0 = time.perf_counter()
    loss1 = self.zo_forward(model, inputs)
    torch.cuda.synchronize()
    stats["forward"] += time.perf_counter() - t0
    
    # === Perturb (-) ===
    torch.cuda.synchronize()
    t0 = time.perf_counter()
    self._perturb_parameters(scaling_factor=-2)
    torch.cuda.synchronize()
    stats["perturb"] += time.perf_counter() - t0
    
    # === Forward (-) ===
    torch.cuda.synchronize()
    t0 = time.perf_counter()
    loss2 = self.zo_forward(model, inputs)
    torch.cuda.synchronize()
    stats["forward"] += time.perf_counter() - t0
    
    self.projected_grad = ((loss1 - loss2) / (2 * self.args.zo_eps)).item()

    # === Restore (+) ===
    torch.cuda.synchronize()
    t0 = time.perf_counter()
    self._perturb_parameters(scaling_factor=1)
    torch.cuda.synchronize()
    stats["perturb"] += time.perf_counter() - t0
    
    # === Update ===
    torch.cuda.synchronize()
    t0 = time.perf_counter()
    self._update_zoadamu()
    torch.cuda.synchronize()
    stats["update"] += time.perf_counter() - t0
    
    self._last_step_stats = stats
    return loss1

def profiled_fzoo_step(self, model, inputs, num_items_in_batch=None):
    """
    FZOO detailed time profiling (Multi-sample sampling).
    Logic adjusted to correctly handle multiple seeds and gradient vectors.
    """
    stats = {"perturb": 0.0, "forward": 0.0, "update": 0.0}
    
    # FZOO logic involves a loop inside zo_step. We dismantle it here for profiling.
    
    self.rand_values = [torch.rand(1).item() for _ in range(len(self.named_parameters_to_optim))]
    self.zo_random_seeds = []
    loss1s = []
    perturbTimes = self.N if self.losses is None else (self.N // 2)
    
    # === Loop for N Perturbations ===
    for i in range(perturbTimes):
        self.zo_random_seed = np.random.randint(1000000000)
        self.zo_random_seeds.append(self.zo_random_seed)
        
        # Perturb
        torch.cuda.synchronize()
        t0 = time.perf_counter()
        self.zo_perturb_parameters(scaling_factor=1)
        torch.cuda.synchronize()
        stats["perturb"] += time.perf_counter() - t0
        
        # Forward
        torch.cuda.synchronize()
        t0 = time.perf_counter()
        with torch.no_grad():
            loss1 = self.zo_forward(model, inputs).detach()
        torch.cuda.synchronize()
        stats["forward"] += time.perf_counter() - t0
        
        loss1s.append(loss1)
        
        # Restore
        torch.cuda.synchronize()
        t0 = time.perf_counter()
        self.zo_perturb_parameters(scaling_factor=-1)
        torch.cuda.synchronize()
        stats["perturb"] += time.perf_counter() - t0

    # Baseline Loss (Unperturbed)
    torch.cuda.synchronize()
    t0 = time.perf_counter()
    with torch.no_grad():
        loss_tensor_gpu = self.zo_forward(model, inputs).detach()
    torch.cuda.synchronize()
    stats["forward"] += time.perf_counter() - t0
    
    # Stats Calculation
    loss1s = torch.tensor(loss1s, dtype=torch.float32)
    loss_tensor_cpu = loss_tensor_gpu.cpu()
    std = torch.std(loss1s, unbiased=False)
    if std == 0 or torch.isnan(std): 
        std = 1.0

    self.projected_grad = ((loss1s - loss_tensor_cpu) / (perturbTimes * std)).tolist()
    
    # === Update ===
    torch.cuda.synchronize()
    t0 = time.perf_counter()
    self.zo_update(model)
    torch.cuda.synchronize()
    stats["update"] += time.perf_counter() - t0
    
    self._last_step_stats = stats
    return loss_tensor_gpu

def profiled_hizoo_step(self, model, inputs, num_items_in_batch=None):
    """HiZOO detailed time profiling"""
    stats = {"perturb": 0.0, "forward": 0.0, "update": 0.0}
    
    model.eval()
    self.zo_random_seed = np.random.randint(1000000000)
    
    # === Forward (Original) ===
    torch.cuda.synchronize()
    t0 = time.perf_counter()
    loss_orig = self.zo_forward(model, inputs)
    torch.cuda.synchronize()
    stats["forward"] += time.perf_counter() - t0
    
    # === Perturb (+) ===
    torch.cuda.synchronize()
    t0 = time.perf_counter()
    self._perturb_hizoo(scaling_factor=1)
    torch.cuda.synchronize()
    stats["perturb"] += time.perf_counter() - t0
    
    # === Forward (+) ===
    torch.cuda.synchronize()
    t0 = time.perf_counter()
    loss1 = self.zo_forward(model, inputs)
    torch.cuda.synchronize()
    stats["forward"] += time.perf_counter() - t0
    
    # === Perturb (-) ===
    torch.cuda.synchronize()
    t0 = time.perf_counter()
    self._perturb_hizoo(scaling_factor=-2)
    torch.cuda.synchronize()
    stats["perturb"] += time.perf_counter() - t0
    
    # === Forward (-) ===
    torch.cuda.synchronize()
    t0 = time.perf_counter()
    loss2 = self.zo_forward(model, inputs)
    torch.cuda.synchronize()
    stats["forward"] += time.perf_counter() - t0
    
    # === Restore (+) ===
    torch.cuda.synchronize()
    t0 = time.perf_counter()
    self._perturb_hizoo(scaling_factor=1)
    torch.cuda.synchronize()
    stats["perturb"] += time.perf_counter() - t0
    
    # === Hessian Update (Considered part of Update overhead) ===
    torch.cuda.synchronize()
    t0 = time.perf_counter()
    self._update_hizoo_hessian(loss_orig, loss1, loss2)
    torch.cuda.synchronize()
    stats["update"] += time.perf_counter() - t0

    self.projected_grad = ((loss1 - loss2) / (2 * self.args.zo_eps)).item()
    
    # === Parameter Update ===
    torch.cuda.synchronize()
    t0 = time.perf_counter()
    self._update_hizoo()
    torch.cuda.synchronize()
    stats["update"] += time.perf_counter() - t0
    
    self._last_step_stats = stats
    return loss1

def profiled_pzo_step(self, model, inputs, num_items_in_batch=None):
    """PseuZO (PZO) detailed time profiling"""
    stats = {"perturb": 0.0, "forward": 0.0, "update": 0.0}
    
    model.eval()
    
    # Momentum Schedule (overhead -> update)
    self._update_momentum_coefficient()

    # === Forward 0 (Gradient Retrieval) ===
    torch.cuda.synchronize()
    t0 = time.perf_counter()
    loss0, o0, grad_last = self.pzo_forward(model, inputs, need_grad=True)
    self.grad_last = grad_last[0] if isinstance(grad_last, tuple) else grad_last 
    torch.cuda.synchronize()
    stats["forward"] += time.perf_counter() - t0

    # Seed
    seed = np.random.randint(1e9)
    self.zo_random_seed = seed
    
    # === Perturb (+) ===
    torch.cuda.synchronize()
    t0 = time.perf_counter()
    self._perturb_mezo(1)
    torch.cuda.synchronize()
    stats["perturb"] += time.perf_counter() - t0
    
    # === Forward 1 (State Retrieval) ===
    torch.cuda.synchronize()
    t0 = time.perf_counter()
    loss1, o1, _ = self.pzo_forward(model, inputs, need_grad=False)
    torch.cuda.synchronize()
    stats["forward"] += time.perf_counter() - t0
    
    # === Restore (-) ===
    torch.cuda.synchronize()
    t0 = time.perf_counter()
    self._perturb_mezo(-1)
    torch.cuda.synchronize()
    stats["perturb"] += time.perf_counter() - t0
    
    # Window Update
    o_diff = o1 - o0
    self.sliding_window.append((seed, o_diff))
    
    # === Update ===
    torch.cuda.synchronize()
    t0 = time.perf_counter()
    self._update_pzo()
    torch.cuda.synchronize()
    stats["update"] += time.perf_counter() - t0
    
    self._last_step_stats = stats
    return loss1

# =============================================================================
# QZO & LQZO Profiled Steps
# =============================================================================

def profiled_qzo_step(self, model, inputs, num_items_in_batch=None):
    """
    QZO training step with detailed timing profiling.
    Mimics standard ZO step but operates on quantized scales.
    """
    stats = {"perturb": 0.0, "forward": 0.0, "update": 0.0}
    
    self.zo_random_seed = np.random.randint(1000000000)
    
    # === Perturb (+) ===
    torch.cuda.synchronize()
    t0 = time.perf_counter()
    self._perturb_qzo(scaling_factor=1)
    torch.cuda.synchronize()
    stats["perturb"] += time.perf_counter() - t0
    
    # === Forward (+) ===
    torch.cuda.synchronize()
    t0 = time.perf_counter()
    loss1 = self.zo_forward(model, inputs)
    torch.cuda.synchronize()
    stats["forward"] += time.perf_counter() - t0
    
    # === Perturb (-) ===
    torch.cuda.synchronize()
    t0 = time.perf_counter()
    self._perturb_qzo(scaling_factor=-2) # Net -1
    torch.cuda.synchronize()
    stats["perturb"] += time.perf_counter() - t0
    
    # === Forward (-) ===
    torch.cuda.synchronize()
    t0 = time.perf_counter()
    loss2 = self.zo_forward(model, inputs)
    torch.cuda.synchronize()
    stats["forward"] += time.perf_counter() - t0
    
    self.projected_grad = ((loss1 - loss2) / (2 * self.args.zo_eps)).item()
    
    # === Restore (+) ===
    torch.cuda.synchronize()
    t0 = time.perf_counter()
    self._perturb_qzo(scaling_factor=1) # Net 0
    torch.cuda.synchronize()
    stats["perturb"] += time.perf_counter() - t0
    
    # === Update ===
    torch.cuda.synchronize()
    t0 = time.perf_counter()
    if self.args.momentum:
        self._update_qzo_momentum()
    else:
        self._update_qzo()
    torch.cuda.synchronize()
    stats["update"] += time.perf_counter() - t0
    
    self._last_step_stats = stats
    return loss1

def profiled_lqzo_step(self, model, inputs, num_items_in_batch=None):
    """
    LQZO training step with detailed timing profiling.
    Uses low-rank perturbation logic internally.
    """
    # LQZO structure is identical to QZO in the Trainer (via inheritance),
    # but the internal _perturb_qzo method dispatches to _perturb_lqzo.
    # We reuse the same profiling wrapper.
    if hasattr(self, "step_counter"):
        self.step_counter += 1
        
    return profiled_qzo_step(self, model, inputs, num_items_in_batch)

# =============================================================================
# Additional Profiled Step Functions for Ada-Series Methods
# =============================================================================

def profiled_adalezo_step(self, model, inputs, num_items_in_batch=None):
    """AdaLeZO detailed time profiling"""
    stats = {"perturb": 0.0, "forward": 0.0, "update": 0.0}
    
    # 1. Active Layer Selection (Overhead -> Update)
    torch.cuda.synchronize()
    t0 = time.perf_counter()
    if self.state.global_step % self.args.adalezo_interval == 0 and self.state.global_step > 0:
        self._resample_layers()
    torch.cuda.synchronize()
    stats["update"] += time.perf_counter() - t0

    self.zo_random_seed = np.random.randint(1000000000)
    
    # === Perturb (+) ===
    torch.cuda.synchronize()
    t0 = time.perf_counter()
    self._perturb_active_layers(scaling_factor=1)
    torch.cuda.synchronize()
    stats["perturb"] += time.perf_counter() - t0
    
    # === Forward (+) ===
    torch.cuda.synchronize()
    t0 = time.perf_counter()
    loss1 = self.zo_forward(model, inputs)
    torch.cuda.synchronize()
    stats["forward"] += time.perf_counter() - t0
    
    # === Perturb (-) ===
    torch.cuda.synchronize()
    t0 = time.perf_counter()
    self._perturb_active_layers(scaling_factor=-2) # +1 -> -1
    torch.cuda.synchronize()
    stats["perturb"] += time.perf_counter() - t0
    
    # === Forward (-) ===
    torch.cuda.synchronize()
    t0 = time.perf_counter()
    loss2 = self.zo_forward(model, inputs)
    torch.cuda.synchronize()
    stats["forward"] += time.perf_counter() - t0
    
    # Gradient Estimate
    self.projected_grad = ((loss1 - loss2) / (2 * self.args.zo_eps)).item()
    
    # === Restore (+) ===
    torch.cuda.synchronize()
    t0 = time.perf_counter()
    self._perturb_active_layers(scaling_factor=1) # -1 -> 0
    torch.cuda.synchronize()
    stats["perturb"] += time.perf_counter() - t0
    
    # === Update (IPW + Bandit Stats) ===
    torch.cuda.synchronize()
    t0 = time.perf_counter()
    self._update_adalezo()
    torch.cuda.synchronize()
    stats["update"] += time.perf_counter() - t0
    
    self._last_step_stats = stats
    return loss1

def profiled_adalozo_step(self, model, inputs, num_items_in_batch=None):
    """
    AdaLoZO detailed time profiling.
    """
    # 1. Measure V Matrix Update time (Categorized as Update overhead)
    v_update_time = 0.0
    torch.cuda.synchronize()
    t0 = time.perf_counter()
    
    # AdaLoZO Core: Periodically update auxiliary matrix
    if self.state.global_step % self.args.lozo_step_interval == 0:
        self._update_lozo_v()
        
    torch.cuda.synchronize()
    v_update_time = time.perf_counter() - t0

    # 2. Call generic AdaLeZO step (Handles Perturb/Forward/Update)
    # This overwrites self._last_step_stats
    loss = profiled_adalezo_step(self, model, inputs, num_items_in_batch)

    # 3. Add V matrix update time to stats
    self._last_step_stats["update"] += v_update_time
    
    return loss

def profiled_adafzoo_step(self, model, inputs, num_items_in_batch=None):
    """AdaFZoo detailed time profiling"""
    stats = {"perturb": 0.0, "forward": 0.0, "update": 0.0}
    
    # Baseline Loss (Unperturbed)
    torch.cuda.synchronize()
    t0 = time.perf_counter()
    with torch.inference_mode():
        loss_baseline = self.zo_forward(model, inputs)
        loss_baseline_val = loss_baseline.detach().cpu().item()
    torch.cuda.synchronize()
    stats["forward"] += time.perf_counter() - t0
    
    losses = []
    seeds = []
    
    # N Perturbations Loop
    for i in range(self.N):
        seed = np.random.randint(1000000000)
        seeds.append(seed)
        self.zo_random_seed = seed
        
        # Perturb (+)
        torch.cuda.synchronize()
        t0 = time.perf_counter()
        self._perturb_active_layers(scaling_factor=1)
        torch.cuda.synchronize()
        stats["perturb"] += time.perf_counter() - t0
        
        # Forward
        torch.cuda.synchronize()
        t0 = time.perf_counter()
        loss = self.zo_forward(model, inputs)
        losses.append(loss.detach().cpu().item())
        torch.cuda.synchronize()
        stats["forward"] += time.perf_counter() - t0
        
        # Restore (-)
        torch.cuda.synchronize()
        t0 = time.perf_counter()
        self._perturb_active_layers(scaling_factor=-1)
        torch.cuda.synchronize()
        stats["perturb"] += time.perf_counter() - t0

    # Gradient Calculation (CPU overhead -> Update)
    torch.cuda.synchronize()
    t0 = time.perf_counter()
    losses_tensor = torch.tensor(losses, dtype=torch.float32)
    std = torch.std(losses_tensor, unbiased=False).item()
    if std == 0 or np.isnan(std): std = 1.0
    projected_grads = (losses_tensor - loss_baseline_val) / (self.N * std)
    torch.cuda.synchronize()
    stats["update"] += time.perf_counter() - t0
    
    # === Update ===
    torch.cuda.synchronize()
    t0 = time.perf_counter()
    self._update_adafzoo(projected_grads, seeds)
    # Resample check
    if self.state.global_step % self.args.adalezo_interval == 0:
        self._resample_layers()
    torch.cuda.synchronize()
    stats["update"] += time.perf_counter() - t0

    self._last_step_stats = stats
    return loss_baseline

def profiled_adahizoo_step(self, model, inputs, num_items_in_batch=None):
    """AdaHiZOO detailed time profiling"""
    stats = {"perturb": 0.0, "forward": 0.0, "update": 0.0}
    
    self.zo_random_seed = np.random.randint(1000000000)
    
    # Original Forward
    torch.cuda.synchronize()
    t0 = time.perf_counter()
    loss_orig = self.zo_forward(model, inputs)
    torch.cuda.synchronize()
    stats["forward"] += time.perf_counter() - t0
    
    # Perturb (+)
    torch.cuda.synchronize()
    t0 = time.perf_counter()
    self._perturb_active_layers(scaling_factor=1)
    torch.cuda.synchronize()
    stats["perturb"] += time.perf_counter() - t0
    
    # Forward (+)
    torch.cuda.synchronize()
    t0 = time.perf_counter()
    loss1 = self.zo_forward(model, inputs)
    torch.cuda.synchronize()
    stats["forward"] += time.perf_counter() - t0
    
    # Perturb (-)
    torch.cuda.synchronize()
    t0 = time.perf_counter()
    self._perturb_active_layers(scaling_factor=-2)
    torch.cuda.synchronize()
    stats["perturb"] += time.perf_counter() - t0
    
    # Forward (-)
    torch.cuda.synchronize()
    t0 = time.perf_counter()
    loss2 = self.zo_forward(model, inputs)
    torch.cuda.synchronize()
    stats["forward"] += time.perf_counter() - t0
    
    # Restore (+)
    torch.cuda.synchronize()
    t0 = time.perf_counter()
    self._perturb_active_layers(scaling_factor=1)
    torch.cuda.synchronize()
    stats["perturb"] += time.perf_counter() - t0
    
    # === Update (Hessian + Params) ===
    torch.cuda.synchronize()
    t0 = time.perf_counter()
    # Update Hessian estimate first
    self._update_hizoo_hessian(loss_orig, loss1, loss2)
    self.projected_grad = ((loss1 - loss2) / (2 * self.args.zo_eps)).item()
    
    # Call _update_adalezo(). In AdaHiZOOTrainer, this method is overridden 
    # to apply the Hessian preconditioning using self.hizoo_hessian.
    self._update_adalezo()
    
    if self.state.global_step % self.args.adalezo_interval == 0:
        self._resample_layers()
    torch.cuda.synchronize()
    stats["update"] += time.perf_counter() - t0
    
    self._last_step_stats = stats
    return loss1

def profiled_adazoadamu_step(self, model, inputs, num_items_in_batch=None):
    """AdaZOAdaMU detailed time profiling"""
    # Logic is identical to AdaLeZO step structure, but calls _update_adalezo (which is overridden with Adam logic)
    # We can reuse profiled_adalezo_step because the difference is only in the _update_adalezo internal logic,
    # which is already wrapped in the "Update" timing block.
    return profiled_adalezo_step(self, model, inputs, num_items_in_batch)

def profiled_adapzo_step(self, model, inputs, num_items_in_batch=None):
    """AdaPZO detailed time profiling"""
    stats = {"perturb": 0.0, "forward": 0.0, "update": 0.0}
    
    # Momentum Schedule (overhead -> update)
    self._update_momentum_coefficient()

    # Forward 0 (Gradient Retrieval)
    torch.cuda.synchronize()
    t0 = time.perf_counter()
    loss0, o0, grad_last = self.pzo_forward(model, inputs, need_grad=True)
    self.grad_last = grad_last[0] if isinstance(grad_last, tuple) else grad_last
    torch.cuda.synchronize()
    stats["forward"] += time.perf_counter() - t0
    
    self.zo_random_seed = np.random.randint(1000000000)
    
    # Perturb (+)
    torch.cuda.synchronize()
    t0 = time.perf_counter()
    self._perturb_active_layers(scaling_factor=1)
    torch.cuda.synchronize()
    stats["perturb"] += time.perf_counter() - t0
    
    # Forward 1 (State Retrieval)
    torch.cuda.synchronize()
    t0 = time.perf_counter()
    loss1, o1, _ = self.pzo_forward(model, inputs, need_grad=False)
    torch.cuda.synchronize()
    stats["forward"] += time.perf_counter() - t0
    
    # Restore (-)
    torch.cuda.synchronize()
    t0 = time.perf_counter()
    self._perturb_active_layers(scaling_factor=-1)
    torch.cuda.synchronize()
    stats["perturb"] += time.perf_counter() - t0
    
    # === Update (History + Params) ===
    torch.cuda.synchronize()
    t0 = time.perf_counter()
    o_diff = o1 - o0
    
    # Store context
    current_active = list(self.current_active_layers)
    current_probs = self.current_layer_probs_map.copy()
    current_counts = self.current_layer_counts_map.copy()
    k_draws = self.num_active_draws
    self.sliding_window.append((self.zo_random_seed, o_diff, current_active, current_probs, current_counts, k_draws))
    
    step_reward = abs((loss1 - loss0).item())
    self._update_adapzo(step_reward)
    
    if self.state.global_step % self.args.adalezo_interval == 0:
        self._resample_layers()
    torch.cuda.synchronize()
    stats["update"] += time.perf_counter() - t0

    self._last_step_stats = stats
    return loss1

def profiled_adadizo_step(self, model, inputs, num_items_in_batch=None):
    """AdaDiZO detailed time profiling"""
    # AdaDiZO calls super().training_step() (which is AdaLeZO logic)
    # Then periodically calls dizo_step().
    # We wrap this manually.
    
    # 1. Run Standard AdaLeZO Step Profile
    loss = profiled_adalezo_step(self, model, inputs, num_items_in_batch)
    
    # Retrieve stats from the inner call
    stats = self._last_step_stats
    
    # 2. Periodic DiZO Projection
    if self.state.global_step > 0 and self.state.global_step % self.dizo_interval == 0:
        torch.cuda.synchronize()
        t0 = time.perf_counter()
        
        # Note: dizo_step involves multiple perturbations and forwards internally.
        # Ideally, we should profile dizo_step internals too, but for high-level summary,
        # we can categorize the entire projection overhead as "Update" (constraint update)
        # or split it if strict accuracy is needed. 
        # Given it's a periodic "correction", putting it in Update/Overhead is acceptable.
        self.dizo_step(model, inputs)
        
        torch.cuda.synchronize()
        stats["update"] += time.perf_counter() - t0
        
        # Update stats
        self._last_step_stats = stats

    return loss
# =============================================================================
# Mocking Data
# =============================================================================

class DummyDataset(Dataset):
    def __init__(self, length):
        self.length = length
    def __len__(self):
        return self.length
    def __getitem__(self, i):
        return {} 

# =============================================================================
# Main Benchmark Loop
# =============================================================================

def main_test(
        batch_size: int = 16,
        sequence_length: int = 256,
        method: str = "mezo", 
        peft_mode: str = "none", 
        steps: int = 10,
        load_float16: bool = True,
        model_path: str = "facebook/opt-1.3b"
):
    print(f"\n{'='*25} Benchmark Config {'='*25}")
    print(f"Method:     {method.upper()}")
    print(f"PEFT Mode:  {peft_mode.upper()}")
    print(f"Batch Size: {batch_size}")
    print(f"Steps:      {steps}")

    # 1. Args Setup
    args = LMZOTrainingArguments(
        output_dir="./tmp_bench",
        per_device_train_batch_size=batch_size,
        trainer=method,
        use_cpu=False,
        zo_eps=1e-3,
        learning_rate=1e-6,
        # # Method specifics
        # zo_adamu_beta1=0.9, zo_adamu_beta2=0.999,
        # lozo_rank=8, lozo_step_interval=100,
        # hessian_smooth="constant1e-4", 
        # sliding_window_length=14, momentum_fb_max=1.0,
        # fzoo_n=4, adalezo_k_ratio=0.1,
        # # QZO/LQZO Specifics
        quant_method="gptq", zoquantified_scale=1.0, 
        clip_zo_grad=True,
    )

    if peft_mode == "lora":
        args.lora = True; args.lora_r = 8; args.lora_alpha = 16
    elif peft_mode == "prefix":
        args.prefix_tuning = True; args.num_prefix = 5
        args.prefix_init_by_real_act = False; args.reparam = False

    # 2. Load Model
    try:
        print(f"Loading model: {model_path}...")
        model = AutoModelForCausalLM.from_pretrained(model_path, device_map="auto", torch_dtype=torch.float16 if load_float16 else torch.float32)
    except Exception as e:
        print(f"Warning: Could not load {model_path}. Creating Dummy OPT-1.3B. Error: {e}")
        # Note: QZO won't work on dummy non-quantized model, but we keep fallback for generic testing
        config = AutoConfig.from_pretrained("facebook/opt-1.3b")
        model = AutoModelForCausalLM.from_config(config)
        if load_float16: 
            model = model.half()
        model = model.cuda()

    model.eval()

    # 3. PEFT Injection
    if peft_mode == "lora":
        peft_config = LoraConfig(task_type=TaskType.CAUSAL_LM, inference_mode=False, r=args.lora_r, lora_alpha=args.lora_alpha, lora_dropout=0.0)
        model = get_peft_model(model, peft_config)
    elif peft_mode == "prefix":
        from zo_core.tuners.prefix import PrefixTuning 
        PrefixTuning(model, num_prefix=args.num_prefix, reparam=args.reparam, float16=load_float16, init_by_real_act=args.prefix_init_by_real_act)

    # 4. Initialize Trainer
    tokenizer = AutoTokenizer.from_pretrained(model_path, trust_remote_code=True) 
    if tokenizer.pad_token is None:
        tokenizer.pad_token = tokenizer.eos_token
        
    TrainerClass = get_trainer_class(args)
    
    trainer = TrainerClass(
        model=model, args=args,
        train_dataset=DummyDataset(length=100), tokenizer=tokenizer, data_collator=lambda x: x
    )

    # Manually initialize optimizer/scheduler to avoid 'NoneType' error
    trainer.create_optimizer()
    trainer.create_scheduler(num_training_steps=steps)

    # Monkey Patch: Inject the profiled training_step
    print(f"Injecting Profiled Step for method: {method}...")
    
    if method == "mezo":
        trainer.training_step = types.MethodType(profiled_mezo_step, trainer)
    elif method == "lozo":
        trainer.training_step = types.MethodType(profiled_lozo_step, trainer)
    elif method == "zo_adamu":
        trainer.training_step = types.MethodType(profiled_zo_adamu_step, trainer)
    elif method == "fzoo":
        trainer.training_step = types.MethodType(profiled_fzoo_step, trainer)
    elif method == "hizoo":
        trainer.training_step = types.MethodType(profiled_hizoo_step, trainer)
    elif method == "pzo":
        trainer.training_step = types.MethodType(profiled_pzo_step, trainer)
    elif method == "dizo":
        trainer.training_step = types.MethodType(profiled_dizo_step, trainer)
    # --- QZO / LQZO ---
    elif method == "qzo":
        trainer.training_step = types.MethodType(profiled_qzo_step, trainer)
    elif method == "lqzo":
        trainer.training_step = types.MethodType(profiled_lqzo_step, trainer)
    # --- Ada Series ---
    elif method == "adalezo":
        trainer.training_step = types.MethodType(profiled_adalezo_step, trainer)
    elif method == "adalozo":
        trainer.training_step = types.MethodType(profiled_adalozo_step, trainer)
    elif method == "adafzoo":
        trainer.training_step = types.MethodType(profiled_adafzoo_step, trainer)
    elif method == "adahizoo":
        trainer.training_step = types.MethodType(profiled_adahizoo_step, trainer)
    elif method == "adazoadamu":
        trainer.training_step = types.MethodType(profiled_adazoadamu_step, trainer)
    elif method == "adapzo":
        trainer.training_step = types.MethodType(profiled_adapzo_step, trainer)
    elif method == "adadizo":
        trainer.training_step = types.MethodType(profiled_adadizo_step, trainer)
    else:
        print(f"Warning: Profiled step not implemented for {method}. Using default (no detailed breakdown).")

    # Forward wrappers setup
    if not hasattr(model, 'original_forward'): model.original_forward = model.forward

    # Select the correct Forward Wrapper based on the method
    if method in ["pzo", "adapzo"]:
        # PZO-based methods require a specific wrapper to extract gradients and states
        from zo_core.trainer.utils import forward_wrap_with_option_len_pzo
        model.forward = forward_wrap_with_option_len_pzo.__get__(model, type(model))
    elif method in ["fzoo", "adafzoo"]:
        # FZOO-based methods use a dedicated wrapper (handling 'n' argument)
        from zo_core.trainer.utils import forward_wrap_with_option_len_fzoo
        model.forward = forward_wrap_with_option_len_fzoo.__get__(model, type(model))
    else:
        # Other methods (MeZO, LoZO, DiZO, QZO, LQZO, etc.) use the generic wrapper
        from zo_core.trainer.utils import forward_wrap_with_option_len
        model.forward = forward_wrap_with_option_len.__get__(model, type(model))

    # 5. Inputs
    dummy_inputs = {
        "input_ids": torch.randint(100, 1000, (batch_size, sequence_length), device=model.device),
        "attention_mask": torch.ones((batch_size, sequence_length), device=model.device),
        "labels": torch.randint(100, 1000, (batch_size, sequence_length), device=model.device),
        "option_len": torch.tensor([10] * batch_size, device=model.device)
    }

    # --- Start Benchmark ---
    torch.cuda.empty_cache()
    torch.cuda.synchronize()
    static_mem_gb = sum([torch.cuda.memory_allocated(i) for i in range(torch.cuda.device_count())]) / 1024**3
    print(f"Static Memory: {static_mem_gb:.4f} GB")

    # Accumulators
    stats_acc = {"perturb": [], "forward": [], "update": [], "peak_mem": [], "overhead": []}

    print(f"\n{'-'*105}")
    print(f"{'Step':<5} | {'Loss':<10} | {'Perturb(s)':<12} | {'Forward(s)':<12} | {'Update(s)':<12} | {'Peak(GB)':<10} | {'Overhead(MB)':<12}")
    print(f"{'-'*105}")

    # Warmup
    # try:
    trainer.training_step(model, dummy_inputs)
    # except Exception as e:
    #     print(f"Error in warmup: {e}")
    #     return

    for i in range(steps):
        # Reset memory stats
        torch.cuda.empty_cache()
        for d in range(torch.cuda.device_count()): torch.cuda.reset_peak_memory_stats(d)
        
        torch.cuda.synchronize()
        
        # === Run Step ===
        loss = trainer.training_step(model, dummy_inputs)
        # ================
        
        torch.cuda.synchronize()
        
        # Get Time Stats (Fallback to 0 if not profiled)
        current_stats = getattr(trainer, "_last_step_stats", {"perturb": 0, "forward": 0, "update": 0})
        
        # Get Memory Stats
        peak_bytes = sum([torch.cuda.max_memory_allocated(d) for d in range(torch.cuda.device_count())])
        peak_gb = peak_bytes / 1024**3
        overhead_mb = (peak_gb - static_mem_gb) * 1024

        # Print Row
        loss_val = loss.item() if isinstance(loss, torch.Tensor) else loss
        print(f"{i+1:<5} | {loss_val:<10.4f} | {current_stats['perturb']:<12.5f} | {current_stats['forward']:<12.5f} | {current_stats['update']:<12.5f} | {peak_gb:<10.4f} | {overhead_mb:<12.2f}")

        # Accumulate
        stats_acc["perturb"].append(current_stats['perturb'])
        stats_acc["forward"].append(current_stats['forward'])
        stats_acc["update"].append(current_stats['update'])
        stats_acc["peak_mem"].append(peak_gb)
        stats_acc["overhead"].append(overhead_mb)

    # Summary
    print(f"{'='*105}")
    print(f"AVERAGE STATISTICS ({method.upper()} + {peft_mode.upper()})")
    print(f"{'='*105}")
    print(f"Avg Perturb Time : {np.mean(stats_acc['perturb']):.5f} s")
    print(f"Avg Forward Time : {np.mean(stats_acc['forward']):.5f} s")
    print(f"Avg Update Time  : {np.mean(stats_acc['update']):.5f} s")
    print(f"{'-'*105}")
    total_time = np.mean(stats_acc['perturb']) + np.mean(stats_acc['forward']) + np.mean(stats_acc['update'])
    print(f"TOTAL STEP TIME  : {total_time:.5f} s")
    print(f"AVG PEAK MEMORY  : {np.mean(stats_acc['peak_mem']):.4f} GB")
    print(f"AVG OVERHEAD     : {np.mean(stats_acc['overhead']):.2f} MB")
    print(f"{'='*105}")

if __name__ == "__main__":
    Fire(main_test)
    # Example usage:
    # CUDA_VISIBLE_DEVICES=0 python large_models/test_fake_time_memory.py 16 256 mezo none 20 True /workspace/wangfei154/models/facebook/opt-13b